### PR TITLE
feat: add libpillowfight

### PR DESCRIPTION
**Pull request by Aatom1**
Python 3 bindings for libpillowfight

Log: add libpillowfight
Issue: deepin-community/sig-deepin-sysdev-team#235

### CODE REVIEW

**Comment by Aatom1** [comment]
@chenchongbiao OBS没建包

**Comment by Aatom1** [comment]
@chenchongbiao @YukariChiba 这个包在OBS里找不到，麻烦看一下

**Comment by chenchongbiao** [comment]
> @chenchongbiao OBS没建包

建包了

**Pull request merged**
